### PR TITLE
Add Handler type

### LINKED ISSUE #1: Merge `RequestHandler` and `ErrorHandler` interfaces
Technically everywhere in Express can accept both and it just skips over it when the arity is wrong. For example, `app.get(handler, errorHandler)` is valid.

### PR DESCRIPTION
**Pull request by felixfbecker**
Closes #1 

@blakeembrey @typings members what do you think of this? The parameter type is more correct, but we lose the type inference (see failed build)

### CODE REVIEW

**Comment by felixfbecker** [comment]
Decided to remove type inference in favor of the correct typing. Adding it back later is also easier than removing.

**Comment by blakeembrey** [comment]
@felixfbecker If you use overloading instead of a union, it should match the correct type.

**Comment by felixfbecker** [comment]
Sorry, cannot get it to work. Can you show me what you mean? Or do a PR?

**Comment by blakeembrey** [comment]
Damn, you're right - I wonder if this is something we can bring up with TypeScript.

**Comment by blakeembrey** [comment]
I would have imagined the union to work, but it's not...

**Comment by blakeembrey** [comment]
I'm guessing it's related to (can't remember the correct word) but how a function with different args is actually compatible with another function in TypeScript. However, for inferencing, I wonder if this could be improved.

**Pull request merged**
