### PR TITLE
Fix up `express()` return type

### PR DESCRIPTION
**Pull request by blakeembrey**
Modifying the prototype is part of middleware in Express, that's how it accepts raw HTTP.

Closes https://github.com/types/npm-express/issues/18. 

@felixfbecker I tried to make the minimal amount of changes, the description of why is in the linked repo 😄 If this makes sense, feel free to merge and update the registry, hoping to use these changes soon because I've been messing around with refactoring the underlying HTTP layer.

### CODE REVIEW

**Comment by felixfbecker** [comment]
Are you sure that `createApplication` returns an interface that is different from `Application`? Can you point me to the source? I was under the impression that `createApplication` returns an `Application`, and the `Application` interface implements the HTTP server interface.

**Comment by blakeembrey** [comment]
Yes, definitely. Express is designed to accept the raw HTTP objects and alters them to add Express.js-specifics. See https://github.com/expressjs/express/blob/bd47aeb88d28c6cff6e2d8e5378ec73c262e039f/lib/express.js#L37-L39 for the handler code, then https://github.com/expressjs/express/blob/bd47aeb88d28c6cff6e2d8e5378ec73c262e039f/lib/application.js#L157-L174 which is the `.handle` function (notice `callback` defaults to `finalhandler`). You'll notice none of this changes the `req` and `res` objects yet from raw HTTP, so you'll find `this._router` (aka `lazyrouter`) does https://github.com/expressjs/express/blob/bd47aeb88d28c6cff6e2d8e5378ec73c262e039f/lib/application.js#L144 which uses https://github.com/expressjs/express/blob/bd47aeb88d28c6cff6e2d8e5378ec73c262e039f/lib/middleware/init.js#L28-L29 (aka change the HTTP request and response prototypes to Express.js' request and response prototypes which internally extend the raw HTTP request and response prototypes anyway (see https://github.com/expressjs/express/blob/bd47aeb88d28c6cff6e2d8e5378ec73c262e039f/lib/request.js#L31).

**Comment by winksaville** [comment]
Is this going to merged into master?

**Comment by felixfbecker** [comment]
Sorry, forgot about this. @blakeembrey I assume the node typings are outdated by now again, but LGTM otherwise.

**Review by felixfbecker — APPROVED** [review]

**Comment by blakeembrey** [comment]
@felixfbecker Since it's a global and the types are used correctly, it won't be a problem.

**Comment by winksaville** [comment]
Txs for merging, I just installed it and then did:
```
$ typings info express
KEY         VALUE                   
name        express                 
source      npm                     
homepage                            
description                         
updated     2017-02-17T20:54:33.000Z
versions    1                       
```

And there is no `homepage` or `description` fields and the 'versions' is 1. I see in the package.json file there is a `description` and a `version` field but no `homepage` field:
```
{
  "name": "typed-express",
  "version": "1.0.0",
  "private": true,
  "description": "Typings for express",
  "scripts": {
    "build": "typings bundle -o test/bundle.d.ts",
    "test": "tsc -p test",
    "lint": "tslint -c tslint.json index.d.ts lib/**/*.d.ts test/**/*.ts"
  },
  "author": "Felix Becker <felix.b@outlook.com>",
  "license": "ISC",
  "devDependencies": {
    "tslint": "^4.3.1",
    "typescript": "^2.1.5",
    "typings": "^2.1.0"
  }
}
```
So I'm a little confused, why is `description` empty?

Is info `versions` a count, it seems to be as typings info express --versions only show one:
```
$ typings info express --versions
TAG                   VERSION DESCRIPTION COMPILER LOCATION                                                          UPDATED                 
4.14.0+20170217205433 4.14.0                       github:types/npm-express#0b8501d546a03055e30749ac9d91fef351319af7 2017-02-17T20:54:33.000Z
```
But why is there only one version I would have expected there to be at least
two, is it because package.json `version` wasn't bumped, if so should the
package.json `version` field be bumped?

Should `homepage` be added to the package.json?

**Comment by blakeembrey** [comment]
Those fields are defined on the registry itself. Usually reserved for information about the definition vs a regular description of the interface, but I don't think anyone uses it (except once). The versions listed from Typings is also all the current definitions in the registry, the old ones continue working but they are hidden behind a deprecated flag - it'd be a bit annoying seeing every change ever merged so we just show the currently listed registry versions.

**Comment by winksaville** [comment]
As a user how do I know if I have the latest version of a particular module and which repo it came from?

**Comment by blakeembrey** [comment]
In the snippet you pasted above, see the location.

**Comment by winksaville** [comment]
Needing to use `typings info express --version` and then seeing a partial url for the location doesn't seem very friendly. It seems to me `typings info express` should be enough and then homepage, description and version should display information for the package which is what people would be interested in. If you wanted the "registry" maybe just `typings info` would display the registry information.

**Comment by blakeembrey** [comment]
What if different versions are from different repos? What about showing the commit, which might be different across versions? I don't see the issue with the current approach considering most people don't really care where it's from and Typings is in maintenance mode since TypeScript has `@types` now. If anything, it might be worth printing the version information on the same screen as the rest to make it easier.

**Comment by winksaville** [comment]
I didn't realize Typings is in maintenance mode. Do you use `npm @types/express` or something else?

I ask because `npm install @types/express` index.d.ts is totally different from what is returned by `typings install express`
```
$ wc node_modules/@types/express/index.d.ts
  74  280 2562 node_modules/@types/express/index.d.ts
$ wc typings/modules/express/index.d.ts 
 1716  8092 65509 typings/modules/express/index.d.ts
```

**Comment by felixfbecker** [comment]
@winksaville see https://github.com/Microsoft/types-publisher/issues/4

**Comment by winksaville** [comment]
@felixfbecker so it looks like someday, maybe sooner maybe later, this will be fixed :(

In the meantime which would you recommend I use, the versions of `.d.ts` files using `typings install xxx` or those from `npm install @typs/xxx`?

**Comment by blakeembrey** [comment]
I'm still going to maintain Typings while people are using it, but I'm not going to promote it over the official solution TypeScript has created. See #14 for information on that point - we still can't publish anything to NPM unfortunately (which is why I haven't officially deprecated Typings yet).

**Pull request merged**
